config/routes.rb
PplInstallationPlanning::Application.routes.draw do
  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end


  resources :installations
  match '/installations/move' => 'installations#move'
  match '/installations/resize' => 'installations#resize'
  match '/installations/drop' => 'installations#drop'

  resources :projects
  resources :teams
end

app/models/installation.rb
class Installation
  STATES = %w(to_plan planned open to_charge finished)
  include Mongoid::Document
  include Ppl::Document

  field :start_on, type: Date
  field :end_on, type: Date
  field :description, type: String
  field :note, type: String
  field :state, type: String, default: :to_plan

  belongs_to :team
  belongs_to :project

  validates :description, :team, presence: true

  before_save :change_state

  def as_json(options = {})
    {
      title: "[#{project.try(:name)}] #{description}",
      start: start_on,
      end: end_on,
      id: id,
      color: team.color,
      show_url: Rails.application.routes.url_helpers.installation_path(id)
    }
  end

  scope :to_plan, where(start_on: nil, end_on: nil)
  scope :past, -> { lt(end_on: Date.today) }

  def move(nb_days)
    self.start_on += nb_days.to_i.days
    self.end_on += nb_days.to_i.days
    self.save
    self
  end

  def resize(nb_days)
    self.end_on += nb_days.to_i.days
    self.save
    self
  end

  def drop(date)
    self.start_on = date.to_date
    self.end_on = start_on
    self.save
    self
  end

  private

  def change_state
    if (start_on && end_on) && state == "to_plan"
      self.state = :planned
    end
  end
end

app/models/project.rb
class Project
  STATES = [:open, :closed]

  include Mongoid::Document
  include Ppl::Document

  field :name, type: String
  field :planned, type: Integer
  field :state, type: String, default: :open
  field :delivery_on, type: Date

  has_many :installations

  scope :active, where(state: :open)
  scope :closed, where(state: :closed)

  def delivery
    delivery_on.strftime("%y.%W") if delivery_on
  end
end

app/models/team.rb
class Team
  include Mongoid::Document
  include Ppl::Document
  field :name, type: String
  field :color, type: String

  has_many :installations
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #:recoverable, :rememberable, :trackable, :validatable
  #devise :database_authenticatable, :omniauthable
  devise :omniauthable

  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :uid, type: String

  def self.find_for_googleapps_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    oauth = access_token['credentials']

    if user = User.where(:email => data['email']).first
      return user
    else #create a user with stub pwd
      User.create!(
        email:  data['email'],
        password: Devise.friendly_token[0,20],
        first_name: data['first_name'],
        last_name: data['last_name'],
        uid: access_token['uid'],
        provider: access_token['provider']
      )
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.googleapps_data'] && session['devise.googleapps_data']['user_info']
        user.email = data['email']
      end
    end
  end

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @installations_to_plan = Installation.to_plan.includes(:team, :project)
    @open_projects = Project.active
    @closed_projects = Project.closed
    @teams = Team.all
  end
end

app/controllers/installations_controller.rb
class InstallationsController < InheritedResources::Base
  respond_to :json, :html

  def index
    start_on = Time.at(params[:start].to_i).to_date - 1.day
    end_on = Time.at(params[:end].to_i).to_date + 1.day
    respond_with Installation.where(end_on: start_on..end_on).includes(:team)
  end

  def move
    render json: Installation.find(params[:id]).move(params[:days])
  end

  def resize
    render json: Installation.find(params[:id]).resize(params[:days])
  end

  def drop
    render json: Installation.find(params[:id]).drop(params[:date])
  end

  def create
    create! { root_url }
  end

  def destroy
    destroy! { root_url }
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_apps
    @user = User.find_for_googleafederated(request.env["omniauth.auth"], current_user)
    #logger.debug request.env['omniauth.auth'].to_yaml
    logger.debug "---------------------"
    logger.debug request.env["omniauth.auth"]

    flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"

    sign_in_and_redirect @user, :event => :authentication
  end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  respond_to :json, :html

  def update
    update! { root_url }
  end

  def create
    create! { root_url }
  end
end

app/controllers/teams_controller.rb
class TeamsController < InheritedResources::Base
  respond_to :html, :json, :js

  def update
    update! { root_url }
  end
  def create
    create! { root_url }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def add_link_to(txt, data=nil)
    content_tag :small do
      link_to send("new_#{txt}_path"), data do
        "<i class='icon icon-plus'></i> ".html_safe + t(['.add',txt].join('_'))
      end
    end
  end

  def add_link_to_modal(url, txt)
    add_link_to url, txt, data: {toggle: "modal"}
  end
end

app/helpers/installations_helper.rb
module InstallationsHelper
end

app/views/home/index.html.haml
.row-fluid
  .span8
    #calendar{data: { path: installations_path}}
  .span4.sidebar
    %h4
      = t '.teams'
      = add_link_to 'team'
    #teams= render @teams

    %h4
      = t '.installations_to_plan'
      = add_link_to 'installation'

    %ul.nav.nav-tabs.nav-stacked#draggable
      - @installations_to_plan.each do |i|
        %li.installation{data: {event_id: i.id, event_title: i.description, event_color: i.team.color}}
          %i.icon.icon-move
          = i.description
          .label.label-warning= i.project.try(:name)
          = render i.team
          .edit.pull-right
            = link_to edit_installation_path(i), class: 'tt', title: t('.edit_installation') do
              %i.icon.icon-edit
            = link_to installation_path(i), class: 'tt', title: t('.delete_installation'), method: :delete do
              %i.icon.icon-remove
    %h4
      = t '.open_projects'
      = add_link_to 'project'
    .modal.hide.fade#add_project
      = render 'projects/form', project: Project.new

    %ul.nav.nav-tabs.nav-stacked
      - @open_projects.each do |p|
        %li= render p

    %h4= t '.closed_projects'
    %ul.nav.nav-tabs.nav-stacked
      - @closed_projects.each do |p|
        %li= link_to p.name, project_path(p)

app/views/installations/_form.html.haml
= semantic_form_for @installation, html: { class: 'validable form-horizontal' } do |i|
  %h3= t @installation.form_title
  = i.input :description, input_html: { class: 'span8 required' }
  = i.input :state, collection: Installation::STATES
  = i.input :team, input_html: { class: 'required' }
  = i.input :project
  = i.input :note, as: :text, input_html: { class: 'span8 redactor' }
  = i.action :submit
  = link_to t('back'), :back, class: "btn btn-warning"

app/views/installations/_installation.html.haml
.row-fluid
  .span6
    - if installation.project
      = render installation.project
    %h3.description
      .label.label-info= installation.state
      = render installation.team
      = installation.description

    .note= installation.note.try(:html_safe)

  .span6
    %pre Il faut que le calendrier soit centré sur la date du travail et peut-être affiché en format semaine ?
    #calendar{data: { path: installations_path}}

app/views/installations/edit.html.haml
.modal{style: "width: 900px; margin-left:-450px;"}= render 'form', installation: @installation

app/views/installations/new.html.haml
= render 'form'

app/views/installations/show.html.haml
%h2
  = t '.title'
  %small
    = link_to t('.edit'), edit_installation_path(@installation)

= render @installation

= @access_token.get('http://docs.google.com/feeds/documents/private/full').to_xml

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
- if user_signed_in?
  #user-nav.navbar.navbar-inverse.navbar-fixed-top
    .navbar-inner
      .container-fluid
        =link_to "PPL Planificator", root_path, class: "brand"
        %ul.nav.pull-right
          %li
            = t '.logged_in_as', user_name: current_user.name
          %li
            =link_to destroy_user_session_path do
              %i.icon.icon-share-alt
              = t('.logout')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Ppl Installation Planning"
      %meta{:content => content_for?(:description) ? yield(:description) : "Ppl Installation Planning", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    = render 'layouts/navigation'
    #main.page-container{:role => "main"}
      .container-fluid
        = render 'layouts/messages'
        = yield
        %footer

app/views/projects/_form.html.haml
= semantic_form_for project, validate: true, html: { class: 'validable form-horizontal' } do |i|
  %h3= t project.form_title
  = i.input :name, input_html: { class: 'required' }
  = i.input :planned, prepend: t('.day')
  = i.input :state, collection: Project::STATES
  = i.input :delivery_on, input_html: { class: 'datepicker' }
  = i.action :submit
  = link_to t('back'), :back, class: "btn btn-warning"

app/views/projects/_project.html.haml
= link_to project_path(project), class: 'tt', title: t('.show_project') do
  - if project.delivery
    .label.label-info= project.delivery
  = project.name
  .badge= "#{project.planned} days"

app/views/projects/edit.html.haml
= render 'form', project: @project

app/views/projects/new.html.haml
= render 'form', project: @project

app/views/projects/show.html.haml
%h1
  Projet
  = @project.name
  - if @project.delivery
    .label.label-info= @project.delivery
  .label.label-warning= @project.state
  %small= link_to t('.edit'), edit_project_path(@project)

%dl
  %dt Nb jours planifie
  %dd= @project.planned

%h2 liste des travaux à planifier

%ul
  - @project.installations.to_plan.each do |i|
    %li= i.description

%h2 liste des travaux terminés

%ul
  - @project.installations.past.each do |i|
    %li= i.description